"""Create a Bambu project containing only assembly modules 2, 3, and 5.

This is an inspection/selection project, not a one-plate print job: module 2
alone nearly fills the X2D bed.  Print the three existing single-part projects
when manufacturing them.
"""
import json
import re
import subprocess
import tempfile
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
STL = ROOT / "stl"
BAMBU = "/Applications/BambuStudio.app/Contents/MacOS/BambuStudio"
PROFILES = {
    "production": (["module_2", "module_3", "module_5"], "modules-2-3-5-view-x2d-pla.3mf", "modules-2-3-5-view.json"),
    "narrow": (["module_2_narrow_visual", "module_5_narrow_visual"], "modules-2-5-narrow-visual-x2d-pla.3mf", "modules-2-5-narrow-visual.json"),
}
profile = sys.argv[1] if len(sys.argv) > 1 else "production"
if profile not in PROFILES:
    raise SystemExit(f"usage: {Path(__file__).name} [{'|'.join(PROFILES)}]")
PARTS, output_name, audit_name = PROFILES[profile]
OUT = ROOT / "print" / "projects" / output_name
AUDIT = ROOT / "audit" / audit_name

with tempfile.TemporaryDirectory() as temp:
    raw = Path(temp) / "raw.3mf"
    subprocess.run([BAMBU, *[str((STL / f"{name}.stl").resolve()) for name in PARTS],
                    "--arrange", "1", "--ensure-on-bed", "--export-3mf", str(raw)], check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    with zipfile.ZipFile(raw) as source:
        entries = {item.filename: source.read(item.filename) for item in source.infolist()}

settings_name = "Metadata/project_settings.config"
settings = json.loads(entries[settings_name])
settings.update({
    "printer_model": "Bambu Lab X2D",
    "printable_area": ["0x0", "256x0", "256x256", "0x256"],
    "printable_height": "260", "wall_loops": "4",
    "sparse_infill_density": "25%", "brim_width": "4",
})
entries[settings_name] = (json.dumps(settings, ensure_ascii=False, indent=4) + "\n").encode()

# Bambu's 3MF model-settings file owns plate membership.  The three modules
# cannot coexist on a 256 mm bed, so give each object a dedicated plate rather
# than leaving the CLI's over-bed multi-object arrangement in the project.
settings_xml = entries["Metadata/model_settings.config"].decode()
settings_root = ET.fromstring(entries["Metadata/model_settings.config"])
objects = []
for obj in settings_root.findall("object"):
    name = next((m.get("value") for m in obj.findall("metadata") if m.get("key") == "name"), None)
    if name in {f"{part}.stl" for part in PARTS}:
        objects.append((obj.get("id"), name))
if {name for _, name in objects} != {f"{part}.stl" for part in PARTS}:
    raise RuntimeError(f"Bambu import did not preserve selected part names: {objects}")

plate_xml = []
for index, (object_id, name) in enumerate(objects, 1):
    plate_xml.append(f'''  <plate>
    <metadata key="plater_id" value="{index}"/>
    <metadata key="plater_name" value="模块 {name.removesuffix('.stl')}"/>
    <metadata key="locked" value="false"/>
    <metadata key="filament_map_mode" value="Manual"/>
    <metadata key="filament_maps" value="1"/>
    <metadata key="filament_volume_maps" value="0"/>
    <model_instance>
      <metadata key="object_id" value="{object_id}"/>
      <metadata key="instance_id" value="0"/>
      <metadata key="identify_id" value="{index}"/>
    </model_instance>
  </plate>''')
    # These compact manifests let Bambu Studio reconstruct the three plates;
    # thumbnails are intentionally omitted and regenerated by the app.
    entries[f"Metadata/plate_{index}.json"] = json.dumps({
        "bbox_all": [], "bbox_objects": [{"id": int(object_id), "name": name}],
        "bed_type": "textured_plate", "version": 2,
    }, ensure_ascii=False).encode()
# The command-line importer creates one default plate containing all objects;
# replace it, rather than append to it, with the three explicit plates.
settings_xml = re.sub(r"\s*<plate>.*?</plate>", "", settings_xml, flags=re.DOTALL)
entries["Metadata/model_settings.config"] = settings_xml.replace("</config>", "\n" + "\n".join(plate_xml) + "\n</config>").encode()

with zipfile.ZipFile(OUT, "w", compression=zipfile.ZIP_DEFLATED) as target:
    for name, content in entries.items():
        target.writestr(name, content)

AUDIT.write_text(json.dumps({
    "status": "passed", "file": OUT.name, "included_parts": PARTS,
    "purpose": f"Bambu Studio {len(PARTS)}-plate project; one selected module per printable plate",
    "print_instruction": "Select the matching plate in Bambu Studio; each plate prints exactly one module.",
}, ensure_ascii=False, indent=2))
print(f"Generated {OUT}")
